export const CARD_CATEGORIES = [
  "Art & Design",
  "Architecture",
  "Animals & Pets",
  "Anime & Manga",
  "Beauty & Skincare",
  "Books & Literature",
  "Business & Finance",
  "Cars & Motorcycles",
  "Celebrities",
  "DIY & Crafts",
  "Education",
  "Entertainment",
  "Fashion & Style",
  "Fitness & Health",
  "Food & Recipes",
  "Gaming",
  "Gardening",
  "Graphic Design",
  "Hair & Hairstyles",
  "History",
  "Home Decor",
  "Humor & Memes",
  "Illustration",
  "Interior Design",
  "Jewelry & Accessories",
  "Kids & Parenting",
  "Landscape",
  "Lifestyle",
  "Luxury",
  "Marketing",
  "Mental Health",
  "Movies & TV",
  "Music",
  "Nature & Outdoors",
  "News & Politics",
  "Photography",
  "Productivity",
  "Quotes & Inspiration",
  "Relationships",
  "Science & Tech",
  "Self Improvement",
  "Shopping",
  "Space & Astronomy",
  "Sports",
  "Tattoos & Body Art",
  "Technology",
  "Travel & Places",
  "Typography",
  "UI/UX Design",
  "Vintage & Retro",
  "Wallpapers",
  "Weddings & Events",
  "Wellness",
  "Other"
]